### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by breescorner** [styyle14/maschine-jam-linux#1]
@styyle14 I was directed here as an idea to my MIDI problem with Maschine Jam from a [Facebook group](https://www.facebook.com/groups/linuxmusicians/permalink/1428694510561898/). I can't get MIDI in or out of the device but lsusb sees it. Will this script help me and if so, how do I use/install it?

I was able to do $make but nothing happens after that...

**Comment by styyle14** [comment]
Hi, just saw your message.

See the updated README.md!

Thanks for opening and issue for this! Hope this helps!
Keep me posted on any suggestions you have or bugs you come across!
I've closed this issue for now unless the instructions need clarification.
Styyle14
